name: Deploy reactjs

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: self-hosted  
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your required Node.js version

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build
          
          sudo cp -r ./build/* /var/www/html

      - name: Restart Nginx
        run: sudo systemctl restart nginx
